Add item requests
RakhmanKichibekov/java-shareit pull request #3
Opened 2022-09-19 20:06 UTC by RakhmanKichibekov

2022-10-05 16:52 UTC, kukolev requested changes

2022-10-05 16:52 UTC, kukolev commented on pom.xml
> +		<dependency>
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (page < 0 || size < 1) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

Аналогично нужно поправить в других подобных местах в коде.

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +        //commentDto.setCreated(comment.getCreated());
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/requests/ItemRequestController.java
> +        Collection<ItemRequestDto> itemRequestDtos = new ArrayList<>();
По моему эту логику лучше вынести в маппер. Потом в маппер просто передавать коллекцию ItemRequest и получать коллекцию ItemRequestDto. Так код маппинга будет в маппере, а не в контроллере.

Аналогично нужно поправить в других методах ниже.

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName().isEmpty() || item.getAvailable() == null || item.getDescription() == null) {
Валидации лучше вынести в отдельный приватный метод. Тогда каждый метод будет отвечать за свою часть функционала и код будет проще анализировать. Код при этом может выглядеть примерно так:

```
public SomeResult someMethod(...) {
    validateSomething(...);
    // business-logic here
}

private void validateSomething(...) {
    if (/* ! check something /*) {
        throw new SomeException();
    }
}

```

Таким образом в методе someMethod визуально будет проще найти бизнес-логику, ради которой этот метод и создавался.

Аналогично нужно поправить в остальных методах в классе.

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.equals("")) {
Лучше сделать проверку так: `if (!"".equals(text))`. Тогда не будет выброшен NullPointerException, если text == null

2022-10-05 16:52 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        ArrayList<UserDto> list = new ArrayList<>();
По моему эту логику лучше вынести в маппер. Потом в маппер просто передавать коллекцию User и получать коллекцию UserDto. Так код маппинга будет в маппере, а не в контроллере.

2022-10-05 16:52 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-10-05 16:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/ControllerTest.java
> +        try {
Перехват исключений здесь лишний, т.к. в нем нет смысла. Нужно убрать блоки try ... catch здесь и в остальных тестах.

2022-10-05 16:52 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/ControllerTest.java
> +    public void findAllBookingsByUser() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

Аналогично нужно поправить и в других подобных случаях.

2022-10-05 21:34 UTC, RakhmanKichibekov commented on pom.xml
> +		<dependency>
поправлено

2022-10-05 21:34 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/item/dto/CommentMapper.java
> +        //commentDto.setCreated(comment.getCreated());
сделал

2022-10-05 21:35 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.equals("")) {
если так сделать то не проходит тесты

2022-10-05 21:35 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (page < 0 || size < 1) {
сделано

2022-10-05 21:55 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName().isEmpty() || item.getAvailable() == null || item.getDescription() == null) {
исправлено

2022-10-05 21:57 UTC, RakhmanKichibekov commented on src/main/resources/application.properties
> +#spring.datasource.driver-class-name=org.postgresql.Driver
сделал

2022-10-06 18:28 UTC, RakhmanKichibekov commented on src/test/java/ru/practicum/shareit/booking/ControllerTest.java
> +        try {
выполнено

2022-10-06 18:41 UTC, RakhmanKichibekov commented on src/test/java/ru/practicum/shareit/booking/ControllerTest.java
> +    public void findAllBookingsByUser() {
сделал

2022-10-07 08:02 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/item/requests/ItemRequestController.java
> +        Collection<ItemRequestDto> itemRequestDtos = new ArrayList<>();
перенёс

2022-10-07 08:02 UTC, RakhmanKichibekov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        ArrayList<UserDto> list = new ArrayList<>();
перенёс

2022-10-08 11:16 UTC, kukolev requested changes

2022-10-08 11:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validation(Item item) {
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

2022-10-08 11:16 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void validation2(Item item,Integer userId){
Нарушение кодстайла: Название метода лучше начинать с глагола, обозначающего действие над аргументами или над классом, которому принадлежит метод. Так назначение метода будет понятно сразу из названия. Нужно поправить.

Также нужно придумать название, которое будет лучше отражать смысл метода.

2022-10-08 11:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/booking/ServiceUnitTest.java
> +    public void findAllStatesBookingsByOwnerTest() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

2022-10-08 11:16 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/RepositoryTest.java
> +    public void findByNameOrDescriptionItemTest() {
Этот тест нужно разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Хороший юнит тест состоит из трех блоков кода:

1. Подготовка данных для теста
2. Вызов тестируемого метода
3. Проверка результатов

Важно, чтобы п.2 выполнялся однократно - так будет проще понять что пошло не так, если один или несколько тестов упадут.

Подробнее о хороших практиках юнит-тестирования можно прочитать тут:  https://www.baeldung.com/java-unit-testing-best-practices

2022-10-09 09:54 UTC, kukolev requested changes

2022-10-09 09:54 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void CheckContentItem(Item item) {
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

2022-10-09 09:54 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void CheckContentItemWithId(Item item, Integer userId){
Нарушение кодстайла: название методов должно быть выполнено в стиле camelCase.

2022-10-09 19:26 UTC, kukolev approved these changes

2022-10-10 16:12 UTC, merged